version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_iot
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ethan
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: iot_agro
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: mongo_iot
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sensors_db
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
