version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_iot
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ethan
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: iot_agro
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ethan -d iot_agro"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: mongo_iot
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sensors_db
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  service-sensors:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: service_sensors
    restart: on-failure
    command: ["node", "service-sensors/server.js"]
    env_file:
      - ./backend/service-sensors/.env
    ports:
      - "3002:3002"
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3002/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  service-parcels:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: service_parcels
    restart: on-failure
    command: ["node", "service-parcels/server.js"]
    env_file:
      - ./backend/service-parcels/.env
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3003/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  service-auth:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: service_auth
    restart: on-failure
    command: ["node", "service-auth/server.js"]
    env_file:
      - ./backend/service-auth/.env
    ports:
      - "3004:3004"
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3004/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mongo_data:
